# Site settings
author: Courtney DeRiggs
title: New to Coding: Make the switch from GUI to CLI
header-img: img/home-bg.png
email: courtney.deriggs@gmail.com
copyright_name: Courtney DeRiggs
description: > # this means to ignore newlines until "baseurl:"
  It's not as hard as you think!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Coder0766

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
